### ISSUE TITLE
Problem with DefaultSimpleModalOptionConfig

### ISSUE THREAD

**Issue by elementalPRESS** [KevCJones/ngx-simple-modal#50] opened 2018-12-01 08:26 UTC
Hi there,

at first: its a great tool and help when dealing a log with dialogs. But I have some problems:

1. I followed your instractions but I'm unable to setup DefaultSimpleModalOptionConfig. The compiler always says that SimpleModalOptions was not found (file is in the right place.... I guess). So I don't know how to get it to work. Please can you check this and give a working example?
```
provide:[
  {
    provide: DefaultSimpleModalOptionConfig,
    useValue: {...defaultSimpleModalOptions, ...{ closeOnEscape: true, closeOnClickOutside: true }}
  }
]
```
2. when using Bootstrap4 the animations do not work. What's going wrong? Everything else in styling is doing a fine job so far...

Thank you for any help and support,
Lars

**Comment by KevCJones** [comment] 2018-12-01 09:59
Seems like it's regression season again. I guess my first question is have
you looked at the readmes link for the stackblitz demo. It's still in NG5 I
know... Waiting on them to upgrade.

I'll try to put some time in this weekend for both issues. If you have a
small example you want to either stick on stackblitz or similar I can help
from there or copy past your Ng cli output for ng -v here.
Ta

**Comment by Tahiche** [comment] 2019-03-08 09:08
I think i might have encountered a similar issue. Only in AOT compiling. I get a "can´t read property 'split' of undefined", when its trying to split 'wrapperclass' but its undefined.  It seems like "defaultSimpleModalOptions" is not being set under AOT.
In simple-modal-holder-component:
`_component.options = options = Object.assign({}, this.defaultSimpleModalOptions, options);`

I assign global options in providers:
```
{
      provide: DefaultSimpleModalOptionConfig,
      useValue: {...defaultSimpleModalOptions, ...defaultMyCustomModalOptions}
    } 
```

It´s fine with --aot=false, 'this.defaultSimpleModalOptions' is merged correctly with instance options.

![no-aot-ngx](https://user-images.githubusercontent.com/491834/54016948-d4038600-4184-11e9-90c5-789777da90d6.JPG)

But with --aot compiling defaultSimpleModalOptions seems to be empty.

![aot-ngx1](https://user-images.githubusercontent.com/491834/54018680-a10fc100-4189-11e9-8ac3-bdcc32fb63c6.JPG)

![aot-ngx2](https://user-images.githubusercontent.com/491834/54018722-b4bb2780-4189-11e9-9c6f-41d166a892a8.JPG)

I find AOT related issues really hard to pin. Errors are cryptic or general and i can´t seem to find a good way to debug. Functions in decorators that don´t work, private variables that work fine in other scenarios stop being available... nightmare.

**Comment by Tahiche** [comment] 2019-03-08 10:44
Update: It seems like setting the default options via "forRoot" is working fine in AOT (vs providers:[provide: DefaultSimpleModalOptionConfig] which is empty in AOT). 

My custom-modals.module shared/utility module which initiates SimpleModal:
```
@NgModule({
  imports: [
    CommonModule,
    SimpleModalModule.forRoot({container: 'modal-container'},{...defaultSimpleModalOptions, ...defaultMyCustomModalOptions})
  ],
  exports: [... ],
  providers: [
    {
      provide: DefaultSimpleModalOptionConfig,
      useValue: {...defaultSimpleModalOptions, ...defaultMyCustomModalOptions}
    }
  ],
```
Currently it´s redundant as " provide: DefaultSimpleModalOptionConfig" and forRoot() are doing the same. As I said (te least in my case) only forRoot() seems to work under AOT.

**Comment by KevCJones** [comment] 2019-03-09 09:41
Thanks for the info and feeding back your findings. I only use the forRoot
approach currently in my NG7 project, explains why I haven't hit this yet.

While I'm a little busy professionally right now , I am aiming to get some
time to look into things. Feel free to PR a solution if you find it.

Contributors welcome

**Closed** 2019-08-02 22:22 UTC
